version: '3.9'

services:
  postgres:
    image: postgres:15.2
    restart: always
    env_file:
      - secrets/postgres.env
    ports:
      - 5432:5432
    volumes:
      - ../data:/var/lib/postgresql/data

  agartex-app:
    image: agaross.azurecr.io/agar-oss/agartex-app:latest
    restart: always
    env_file:
      - secrets/agartex-app.env
    ports:
      - 80:5000

  agartex-service:
    image: agaross.azurecr.io/agar-oss/agartex-service:latest
    restart: always
    env_file:
      - secrets/agartex-service.env
    ports:
      - 3000:3000
      